<?php

namespace App\Services\Report;

final class ReportVisibleLabels
{
    /** @var array<string, string> */
    private const SECTION_TITLES_ES = [
        'BP-2' => 'Circunstancias específicas de preparación',
        'GOV-1' => 'Función y composición de los órganos de gobierno',
        'GOV-2' => 'Información y asuntos de sostenibilidad tratados por los órganos de gobierno',
        'GOV-4' => 'Declaración sobre diligencia debida',
        'SBM-2' => 'Intereses y opiniones de las partes interesadas',
        'SBM-3' => 'Impactos, riesgos y oportunidades materiales y su relación con la estrategia',
        'IRO-1' => 'Proceso para identificar y evaluar impactos, riesgos y oportunidades materiales',
        'IRO-2' => 'Requisitos de divulgación cubiertos por el informe',
        'E1-1' => 'Plan de transición para el cambio climático',
        'E1.SBM-3' => 'Impactos, riesgos y oportunidades climáticos y su relación con la estrategia',
        'E1-2' => 'Políticas de mitigación y adaptación al cambio climático',
        'E1-3' => 'Acciones y recursos climáticos',
        'E1-4' => 'Objetivos de reducción de emisiones',
        'E1-6' => 'Emisiones brutas de gases de efecto invernadero',
        'E5.IRO-1' => 'Proceso para identificar impactos, riesgos y oportunidades sobre circularidad',
        'E5-1' => 'Políticas de uso de recursos y economía circular',
        'E5-2' => 'Acciones y recursos para la economía circular',
        'E5-3' => 'Objetivos de uso de recursos y economía circular',
        'G1-1' => 'Cultura empresarial y conducta profesional',
        'G1-2' => 'Gestión de las relaciones con proveedores',
        'G1-3' => 'Prevención y detección de corrupción y soborno',
        'G1-4' => 'Casos de corrupción o soborno',
        'G1-5' => 'Influencia política y actividades de representación',
        'G1-6' => 'Prácticas de pago',
        'G1.GOV-1' => 'Funciones de los órganos de gobierno en la conducta empresarial',
        'G1.MDR-P' => 'Políticas sobre conducta empresarial y cultura corporativa',
        'MDR-A' => 'Acciones y recursos para gestionar impactos materiales',
        'MDR-M' => 'Métricas para medir temas materiales',
        'MDR-P' => 'Políticas para gestionar temas materiales',
        'MDR-T' => 'Objetivos y seguimiento del progreso',
        'S1-11' => 'Protección social de la plantilla',
        'S1-2' => 'Procesos de diálogo con la plantilla',
        'S1-3' => 'Mecanismos de reclamación de la plantilla',
        'S1-4' => 'Acciones sobre los impactos en la plantilla',
        'S1-5' => 'Objetivos relativos al personal propio',
        'S1.SBM-3' => 'Personas de la plantilla afectadas materialmente',
        'S2-4' => 'Acciones sobre los trabajadores de la cadena de valor',
        'S2.SBM-3' => 'Trabajadores de la cadena de valor afectados materialmente',
        'S4-1' => 'Políticas sobre consumidores y usuarios finales',
        'S4-3' => 'Canales para consumidores y usuarios finales',
        'S4-4' => 'Acciones sobre consumidores y usuarios finales',
        'S4.SBM-3' => 'Consumidores y usuarios finales afectados materialmente',
        'SBM-1' => 'Estrategia, modelo de negocio y productos o servicios',
    ];

    /** @var array<string, string> */
    private const CLAIM_LABELS_ES = [
        'BP-1_02' => 'Alcance de consolidación del estado de sostenibilidad',
        'E1-1_05' => 'Recursos financieros operativos asignados al plan de acción',
        'E1-1_06' => 'Recursos financieros de inversión asignados al plan de acción',
        'E1-4_01' => 'Existencia y características de objetivos para gestionar impactos, riesgos y oportunidades climáticos',
        'E1-5_02' => 'Consumo total de energía de fuentes fósiles',
        'E1-5_12' => 'Consumo de combustible procedente de gas natural',
        'E1-5_15' => 'Porcentaje de fuentes fósiles en el consumo total de energía',
        'E1-5_18' => 'Intensidad energética de actividades en sectores de alto impacto climático',
        'E1-5_19' => 'Consumo total de energía de actividades en sectores de alto impacto climático',
        'E1-5_20' => 'Sectores de alto impacto climático considerados para la intensidad energética',
        'E1-5_22' => 'Ingresos netos de actividades en sectores de alto impacto climático',
        'E1-5_23' => 'Ingresos netos de actividades ajenas a sectores de alto impacto climático',
        'E1-6_07' => 'Emisiones brutas de alcance 1',
        'E1-6_09' => 'Emisiones brutas de alcance 2 basadas en la ubicación',
        'E1-6_10' => 'Emisiones brutas de alcance 2 basadas en el mercado',
        'E1-6_11' => 'Emisiones brutas de alcance 3',
        'E1-6_12' => 'Emisiones totales de gases de efecto invernadero según ubicación',
        'E1-6_13' => 'Emisiones totales de gases de efecto invernadero según mercado',
        'E1-6_30' => 'Intensidad de emisiones según ubicación',
        'E1-6_31' => 'Intensidad de emisiones según mercado',
        'E1-6_33' => 'Ingresos netos',
        'E1-6_34' => 'Ingresos netos utilizados para calcular la intensidad de emisiones',
        'E1-6_35' => 'Ingresos netos no utilizados para calcular la intensidad de emisiones',
        'G1-1_01' => 'Descripción de la forma de establecer, desarrollar, promover y evaluar la cultura empresarial',
        'G1-1_02' => 'Mecanismos para identificar, comunicar e investigar conductas ilícitas o contrarias al código de conducta',
        'G1-1_05' => 'Garantías para comunicar irregularidades y proteger a quienes las denuncian',
        'G1-1_08' => 'Compromiso de investigar los incidentes de conducta empresarial con prontitud, independencia y objetividad',
        'G1-1_10' => 'Política de formación interna sobre conducta empresarial',
        'G1-1_11' => 'Funciones con mayor riesgo de corrupción y soborno',
        'G1-3_01' => 'Procedimientos para prevenir, detectar y abordar casos de corrupción o soborno',
        'G1-3_05' => 'Comunicación de las políticas a las personas destinatarias',
        'G1-3_06' => 'Alcance y características de los programas de formación contra la corrupción y el soborno',
        'G1-3_07' => 'Porcentaje de funciones de riesgo cubiertas por programas de formación',
        'G1-3_08' => 'Miembros de los órganos de administración, supervisión y dirección que reciben formación contra la corrupción y el soborno',
        'G1.GOV-1_01' => 'Funciones de los órganos de administración, dirección y supervisión en la conducta empresarial',
        'G1.MDR-P_01-06' => 'Políticas para gestionar impactos, riesgos y oportunidades materiales sobre conducta empresarial y cultura corporativa',
        'MDR-A_09' => 'Recursos financieros actuales para acciones de inversión',
        'MDR-A_10' => 'Recursos financieros actuales para acciones operativas',
        'MDR-T_02' => 'Objetivo medible',
        'MDR-T_06' => 'Año de referencia',
        'MDR-T_19' => 'Año base para medir el progreso',
        'S1-11_04' => 'Personas de la plantilla cubiertas por protección social frente a la pérdida de ingresos por permiso parental',
        'S1-1_10' => 'Políticas específicas para eliminar la discriminación',
        'S1-1_15' => 'Políticas de contratación, asignación, formación y promoción basadas en cualificaciones y experiencia',
        'S1-1_22' => 'Programas para promover el acceso al desarrollo de capacidades',
        'S1-2_02' => 'Diálogo con la plantilla o sus representantes',
        'S1-3_05' => 'Mecanismos de gestión de reclamaciones sobre asuntos laborales',
        'S1-4_01' => 'Acciones realizadas o previstas para prevenir o mitigar impactos negativos en la plantilla',
        'S1-4_09' => 'Recursos asignados a la gestión de impactos materiales',
        'S1-6_01' => 'Número de empleados por género',
        'S1-6_04' => 'Empleados en países con al menos 50 empleados y el 10 % de la plantilla',
        'S1-6_05' => 'Número de empleados en países con al menos 50 empleados y el 10 % de la plantilla',
        'S1-6_09' => 'Número de empleados según plantilla o equivalencia a tiempo completo',
        'S1-6_11' => 'Número de empleados que han dejado la empresa',
        'S1-6_12' => 'Porcentaje de rotación de empleados',
        'S1-6_13' => 'Metodologías y supuestos utilizados para elaborar los datos de empleados',
        'S1-6_14' => 'Criterio de recuento de empleados: plantilla o equivalencia a tiempo completo',
        'S1-6_15' => 'Momento o método de cálculo del número de empleados',
        'S1-6_16' => 'Información contextual necesaria para comprender los datos de empleados',
        'S1-6_19' => 'Número de empleados a tiempo completo',
        'S1-6_20' => 'Número de empleados a tiempo parcial',
        'S1.SBM-3_01' => 'Personas de la plantilla potencialmente afectadas materialmente incluidas en el alcance de la información',
        'S1.SBM-3_02' => 'Tipos de empleados y no empleados sujetos a impactos materiales',
        'S1.SBM-3_03' => 'Existencia de impactos negativos materiales en la plantilla',
        'S2-4_01' => 'Acciones realizadas o previstas sobre impactos negativos materiales en trabajadores de la cadena de valor',
        'S2-4_06' => 'Enfoque para actuar sobre impactos negativos materiales específicos en trabajadores de la cadena de valor',
        'S2-4_10' => 'Medidas para evitar que las prácticas propias causen o contribuyan a impactos negativos materiales',
        'S2-4_11' => 'Problemas e incidentes graves de derechos humanos en la cadena de valor',
        'S2-4_13' => 'Uso de influencia sobre relaciones comerciales para gestionar impactos negativos materiales',
        'S2.SBM-3_01' => 'Trabajadores de la cadena de valor potencialmente afectados materialmente incluidos en el alcance de la información',
        'S2.SBM-3_02' => 'Tipos de trabajadores de la cadena de valor sujetos a impactos materiales',
        'S4-1_01' => 'Políticas para gestionar impactos, riesgos y oportunidades materiales sobre consumidores y usuarios finales',
        'S4-3_02' => 'Canales para que consumidores y usuarios finales planteen preocupaciones o necesidades',
        'S4-3_04' => 'Seguimiento de los asuntos planteados y de la eficacia de los canales',
        'S4-3_11' => 'Tratamiento confidencial de las reclamaciones y respeto a la privacidad y la protección de datos',
        'S4-3_13' => 'Número de reclamaciones recibidas de consumidores y usuarios finales',
        'S4-4_01' => 'Acciones realizadas o previstas sobre impactos negativos materiales en consumidores y usuarios finales',
        'S4-4_02' => 'Acciones para ofrecer o facilitar reparación ante impactos materiales reales',
        'S4-4_04' => 'Seguimiento y evaluación de la eficacia de las acciones para consumidores y usuarios finales',
        'S4-4_11' => 'Problemas e incidentes graves de derechos humanos relacionados con consumidores y usuarios finales',
        'S4.SBM-3_01' => 'Consumidores y usuarios finales potencialmente afectados materialmente incluidos en el alcance de la información',
        'S4.SBM-3_02' => 'Tipos de consumidores y usuarios finales sujetos a impactos materiales',
        'S4.SBM-3_03' => 'Tipos de consumidores y usuarios finales sujetos a impactos materiales por operaciones propias o cadena de valor',
        'SBM-1_01' => 'Grupos significativos de productos y servicios ofrecidos',
        'SBM-1_03' => 'Número total de empleados',
        'SBM-1_04' => 'Número de empleados',
        'SBM-1_06' => 'Ingresos totales',
    ];

    public static function sectionTitle(string $drKey): ?string
    {
        return self::SECTION_TITLES_ES[$drKey] ?? null;
    }

    public static function claimLabel(string $datapointId): ?string
    {
        return self::CLAIM_LABELS_ES[$datapointId]
            ?? ReportVisibleCorpusLabels::claimLabel($datapointId);
    }
}
